### PR TITLE
Wishlist: Prevent exiting fullscreen mode when pointer exits window

### PR DESCRIPTION
**Pull request by Technium**
Normally fullscreen mode is cancelled when the pointer leaves the window - I find this very frustrating. It seems that hacking the Flash binary is one way to disable this behaviour . Sadly this needs to be re-hacked every time the binary is updated so is not a good solution.

I wonder if it is possible to achieve the same effect via an extension to this LD_PRELOAD?  Perhaps remove LeaveWindow events? Maybe only when in fullscreen mode? Not sure, but it would seem like there's a chance of making this work.

I'll have play with this eventually and see if I can make it work but if anyone can achieve it quickly and easily then great :)

### CODE REVIEW

**Comment by ali1234** [comment]
I'm aware of this problem and gave some thought to it, but I couldn't see any easy way to make it work. Can you give some links to existing workarounds?

**Comment by Technium** [comment]
There is an automatic patcher that has fairly readable source at http://deve.loping.net/projects/ignoflash/. Although it is out of date now it does have well commented source that gives a number of clues of places to look and approaches to take.

**Comment by Technium** [comment]
After much experimentation I have this working by simply masking out PropertyChange in XSelectInput. I'll clean it up and make it public after a bit more testing.

**Comment by ali1234** [comment]
Can you rebase this please? And remove those whitespace changes. Thanks.

**Comment by ali1234** [comment]
Merged.

**Pull request closed without merging**
